title: "AtCoder ã‚¬ãƒè¨€èª Haskell ğŸ”¥"
summary: "Haskell ã§ AtCoder ã«å…¥é–€ã—ã¾ã—ã‚‡ã†"
topics: ["haskell"]
published: true
price: 0 # æœ‰æ–™ã®å ´åˆ200ã€œ5000
# æœ¬ã«å«ã‚ã‚‹ãƒãƒ£ãƒ—ã‚¿ãƒ¼ã‚’é †ç•ªã«ä¸¦ã¹ã¾ã—ã‚‡ã†
chapters:
  - cover
  - intro
  - toc

  - 1-getting-started
  - 1-1-hello-world
  - 1-2-abs
  - 1-3-projects
  - 1-3-1-hls
  - 1-3-2-oj

  - 2-haskell-for-atcoder
  - 2-1-stderr
  - 2-2-loops
  - 2-3-arrays
  - 2-3-1-ix
  - 2-3-2-iarray
  - 2-3-3-marray
  - 2-4-vectors
  - 2-4-1-vector
  - 2-4-2-mvector

  - 3-seriously-haskell
  - 3-1-typical-io
  - 3-2-dp
  - 3-3-graphs

  - 4-misc
  - 4-1-real-world
  - 4-2-benchmarking
  - 4-3-split-your-library
  - 4-4-verification-helper
  # - 4-4-interactive-judge
  # - 4-5-view-patterns
  # - 4-6-state

  - end
  - a-judge-env
